---
http_interactions:
- request:
    method: get
    uri: https://api.stripe.com/v1/account
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - "*/*; q=0.5, application/xml"
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - Stripe/v1 RubyBindings/1.14.0
      Authorization:
      - "<AUTH>"
      Content-Type:
      - application/x-www-form-urlencoded
      X-Stripe-Client-User-Agent:
      - '{"bindings_version":"1.14.0","lang":"ruby","lang_version":"2.1.1 p76 (2014-02-24)","platform":"x86_64-darwin13.0","publisher":"stripe","uname":"Darwin
        Mattiass-MacBook-Air.local 13.0.0 Darwin Kernel Version 13.0.0: Thu Sep 19
        22:22:27 PDT 2013; root:xnu-2422.1.72~6/RELEASE_X86_64 x86_64"}'
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx
      Date:
      - Mon, 15 Sep 2014 19:27:07 GMT
      Content-Type:
      - application/json;charset=utf-8
      Content-Length:
      - '1878'
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Methods:
      - GET, POST, HEAD, OPTIONS, DELETE
      Access-Control-Max-Age:
      - '300'
      Cache-Control:
      - no-cache, no-store
      Stripe-Version:
      - '2014-03-13'
      Strict-Transport-Security:
      - max-age=31556926; includeSubDomains
    body:
      encoding: UTF-8
      string: |
        {
          "id": "acct_142w3g2n3roS7mLX",
          "email": "info@acme.com",
          "statement_descriptor": "ACME.COM",
          "display_name": "ACME",
          "timezone": "Etc/UTC",
          "details_submitted": true,
          "charge_enabled": true,
          "transfer_enabled": true,
          "currencies_supported": [
            "usd",
            "aed",
            "afn",
            "all",
            "amd",
            "ang",
            "aoa",
            "ars",
            "aud",
            "awg",
            "azn",
            "bam",
            "bbd",
            "bdt",
            "bgn",
            "bif",
            "bmd",
            "bnd",
            "bob",
            "brl",
            "bsd",
            "bwp",
            "bzd",
            "cad",
            "cdf",
            "chf",
            "clp",
            "cny",
            "cop",
            "crc",
            "cve",
            "czk",
            "djf",
            "dkk",
            "dop",
            "dzd",
            "eek",
            "egp",
            "etb",
            "eur",
            "fjd",
            "fkp",
            "gbp",
            "gel",
            "gip",
            "gmd",
            "gnf",
            "gtq",
            "gyd",
            "hkd",
            "hnl",
            "hrk",
            "htg",
            "huf",
            "idr",
            "ils",
            "inr",
            "isk",
            "jmd",
            "jpy",
            "kes",
            "kgs",
            "khr",
            "kmf",
            "krw",
            "kyd",
            "kzt",
            "lak",
            "lbp",
            "lkr",
            "lrd",
            "lsl",
            "ltl",
            "lvl",
            "mad",
            "mdl",
            "mga",
            "mkd",
            "mnt",
            "mop",
            "mro",
            "mur",
            "mvr",
            "mwk",
            "mxn",
            "myr",
            "mzn",
            "nad",
            "ngn",
            "nio",
            "nok",
            "npr",
            "nzd",
            "pab",
            "pen",
            "pgk",
            "php",
            "pkr",
            "pln",
            "pyg",
            "qar",
            "ron",
            "rsd",
            "rub",
            "rwf",
            "sar",
            "sbd",
            "scr",
            "sek",
            "sgd",
            "shp",
            "sll",
            "sos",
            "srd",
            "std",
            "svc",
            "szl",
            "thb",
            "tjs",
            "top",
            "try",
            "ttd",
            "twd",
            "tzs",
            "uah",
            "ugx",
            "uyu",
            "uzs",
            "vef",
            "vnd",
            "vuv",
            "wst",
            "xaf",
            "xcd",
            "xof",
            "xpf",
            "yer",
            "zar",
            "zmw"
          ],
          "default_currency": "usd",
          "country": "BE",
          "object": "account"
        }
    http_version:
  recorded_at: Mon, 15 Sep 2014 19:27:07 GMT
recorded_with: VCR 2.9.2
